// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqhiyyqmgaitrkxykjsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxaGl5eXFtZ2FpdHJreHlranNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMzg0MTgsImV4cCI6MjA2NzgxNDQxOH0.qIBMkNOeKc2OdV_DpMpiIbwCG10y53KszcN6KIEFFhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});